# Generated by Django 3.2.8 on 2021-10-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_backend_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gig',
            name='rsvps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gig',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
